import { Link } from "react-router-dom";
import {
  ArrowRight,
  Bot,
  CheckCircle2,
  Clock3,
  FileBarChart,
  FileText,
  Gauge,
  Landmark,
  MessageCircle,
  Play,
  Sparkles,
  TrendingUp,
  Users,
  Zap,
} from "lucide-react";

const metrics = [
  { label: "Reports generated", value: "148", detail: "+12% from last month", icon: FileBarChart },
  { label: "Time saved", value: "36.4h", detail: "Across 18 workflows", icon: Clock3 },
  { label: "Completion rate", value: "96.8%", detail: "+2.4% this month", icon: Gauge },
  { label: "Active automations", value: "8", detail: "All running normally", icon: Zap },
];

const activity = [
  { day: "Mon", value: 12 }, { day: "Tue", value: 18 }, { day: "Wed", value: 15 },
  { day: "Thu", value: 24 }, { day: "Fri", value: 21 }, { day: "Sat", value: 8 }, { day: "Sun", value: 14 },
];

const templates = [
  { title: "Portfolio performance", description: "Loan portfolio quality, balances, and risk signals.", cadence: "Weekly", icon: Landmark },
  { title: "Branch operations", description: "Compare activity and service outcomes across branches.", cadence: "Monthly", icon: Users },
  { title: "Executive summary", description: "A concise view of growth, collections, and exceptions.", cadence: "On demand", icon: FileText },
];

const reports = [
  { title: "June portfolio review", source: "Portfolio template", owner: "Operations", date: "Jul 14, 2026", status: "Ready" },
  { title: "Weekly branch pulse", source: "Branch template", owner: "Regional team", date: "Jul 13, 2026", status: "Ready" },
  { title: "Collections exceptions", source: "AI Report Chat", owner: "Risk team", date: "Jul 12, 2026", status: "Processing" },
  { title: "Q2 executive summary", source: "Executive template", owner: "Leadership", date: "Jul 10, 2026", status: "Ready" },
];

export default function DashboardPage() {
  return (
    <div className="space-y-7 pb-8">
      <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between" aria-labelledby="dashboard-heading">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Wednesday, July 15</p>
          <h1 id="dashboard-heading" className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Good morning. Here&apos;s your report activity.</h1>
          <p className="mt-2 max-w-2xl text-sm text-muted-foreground">Review what changed, generate recurring reports, and follow the items that need attention.</p>
        </div>
        <Link to="/chat" className="inline-flex min-h-10 shrink-0 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground shadow-sm hover:bg-primary/90">
          <MessageCircle className="size-4" aria-hidden="true" />Generate with AI
        </Link>
      </section>

      <section aria-labelledby="overview-heading">
        <h2 id="overview-heading" className="sr-only">Reporting overview</h2>
        <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
          {metrics.map((metric) => (
            <article key={metric.label} className="rounded-xl border bg-card p-4 shadow-[var(--shadow-panel)]">
              <div className="flex items-start justify-between gap-3">
                <p className="text-sm text-muted-foreground">{metric.label}</p>
                <span className="grid size-8 place-items-center rounded-lg bg-primary/8 text-primary"><metric.icon className="size-4" aria-hidden="true" /></span>
              </div>
              <p className="mt-4 text-2xl font-semibold tabular-nums tracking-tight">{metric.value}</p>
              <p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><TrendingUp className="size-3.5 text-[var(--status-success)]" aria-hidden="true" />{metric.detail}</p>
            </article>
          ))}
        </div>
      </section>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.65fr)_minmax(18rem,0.75fr)]">
        <section className="rounded-xl border bg-card p-5 shadow-[var(--shadow-panel)]" aria-labelledby="activity-heading">
          <div className="flex items-start justify-between gap-4">
            <div><h2 id="activity-heading" className="font-semibold">Report activity</h2><p className="mt-1 text-sm text-muted-foreground">112 reports generated over the last seven days.</p></div>
            <span className="rounded-full bg-[var(--status-success-soft)] px-2.5 py-1 text-xs font-medium text-[var(--status-success)]">+16% this week</span>
          </div>
          <div className="mt-7 grid h-52 grid-cols-7 items-end gap-2 border-b border-border px-1 sm:gap-4" role="img" aria-label="Reports generated by day: Monday 12, Tuesday 18, Wednesday 15, Thursday 24, Friday 21, Saturday 8, Sunday 14">
            {activity.map((item) => (
              <div key={item.day} className="flex h-full min-w-0 flex-col justify-end gap-2 text-center">
                <span className="text-xs font-medium tabular-nums">{item.value}</span>
                <div className="mx-auto w-full max-w-11 rounded-t-md bg-primary/80" style={{ height: `${item.value * 6}px` }} aria-hidden="true" />
                <span className="pb-2 text-[0.65rem] text-muted-foreground sm:text-xs">{item.day}</span>
              </div>
            ))}
          </div>
        </section>

        <aside className="flex flex-col rounded-xl border border-primary/15 bg-[var(--surface-insight)] p-5" aria-labelledby="insight-heading">
          <span className="mb-5 grid size-10 place-items-center rounded-xl bg-primary text-primary-foreground"><Sparkles className="size-5" aria-hidden="true" /></span>
          <p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">AI insight</p>
          <h2 id="insight-heading" className="mt-2 text-lg font-semibold">Portfolio reviews are taking less time.</h2>
          <p className="mt-3 text-sm leading-6 text-muted-foreground">Template reuse cut average preparation time by 22%. Automating the Friday review could save another 3 hours monthly.</p>
          <Link to="/chat" className="mt-auto inline-flex min-h-10 items-center gap-2 pt-6 text-sm font-semibold text-primary">Explore recommendation <ArrowRight className="size-4" aria-hidden="true" /></Link>
        </aside>
      </div>

      <section aria-labelledby="templates-heading">
        <div className="mb-3 flex items-end justify-between"><div><h2 id="templates-heading" className="font-semibold">Report templates</h2><p className="mt-1 text-sm text-muted-foreground">Start with a trusted structure.</p></div></div>
        <div className="grid gap-3 md:grid-cols-3">
          {templates.map((template) => (
            <article key={template.title} className="flex flex-col rounded-xl border bg-card p-5 shadow-[var(--shadow-panel)]">
              <div className="flex items-start justify-between gap-3"><span className="grid size-9 place-items-center rounded-lg bg-muted text-primary"><template.icon className="size-4" aria-hidden="true" /></span><span className="rounded-full border px-2 py-1 text-[0.65rem] font-medium text-muted-foreground">{template.cadence}</span></div>
              <h3 className="mt-4 font-semibold">{template.title}</h3><p className="mt-2 flex-1 text-sm leading-6 text-muted-foreground">{template.description}</p>
              <Link to="/chat" className="mt-5 inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border bg-background px-3 text-sm font-medium hover:bg-muted"><Play className="size-3.5" aria-hidden="true" />Generate report</Link>
            </article>
          ))}
        </div>
      </section>

      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(16rem,0.6fr)]">
        <section className="overflow-hidden rounded-xl border bg-card shadow-[var(--shadow-panel)]" aria-labelledby="recent-heading">
          <div className="border-b px-5 py-4"><h2 id="recent-heading" className="font-semibold">Recent reports</h2><p className="mt-1 text-sm text-muted-foreground">Latest generated and scheduled work.</p></div>
          <div className="hidden grid-cols-[minmax(12rem,1.5fr)_minmax(8rem,1fr)_8rem_7rem_5rem] gap-4 border-b bg-muted/35 px-5 py-2.5 text-xs font-medium text-muted-foreground 2xl:grid"><span>Report</span><span>Owner</span><span>Date</span><span>Status</span><span>Access</span></div>
          <ul className="divide-y">
            {reports.map((report) => (
              <li key={report.title} className="grid gap-3 px-5 py-4 text-sm 2xl:grid-cols-[minmax(12rem,1.5fr)_minmax(8rem,1fr)_8rem_7rem_5rem] 2xl:items-center 2xl:gap-4">
                <div><p className="font-medium">{report.title}</p><p className="mt-0.5 text-xs text-muted-foreground">{report.source}</p></div>
                <p><span className="mr-2 text-xs text-muted-foreground 2xl:hidden">Owner:</span>{report.owner}</p>
                <p className="tabular-nums text-muted-foreground"><span className="mr-2 text-xs 2xl:hidden">Date:</span>{report.date}</p>
                <span className={`w-fit rounded-full px-2.5 py-1 text-xs font-medium ${report.status === "Ready" ? "bg-[var(--status-success-soft)] text-[var(--status-success)]" : "bg-[var(--status-warning-soft)] text-[var(--status-warning)]"}`}>{report.status === "Ready" ? "✓ " : "● "}{report.status}</span>
                <span className="text-xs text-muted-foreground"><span className="mr-2 2xl:hidden">Access:</span>View only</span>
              </li>
            ))}
          </ul>
        </section>

        <aside className="rounded-xl border bg-card p-5 shadow-[var(--shadow-panel)]" aria-labelledby="status-heading">
          <div className="flex items-center gap-2"><CheckCircle2 className="size-4 text-[var(--status-success)]" aria-hidden="true" /><h2 id="status-heading" className="font-semibold">System status</h2></div>
          <p className="mt-1 text-sm text-muted-foreground">All reporting services are operational.</p>
          <ul className="mt-5 space-y-4 text-sm">
            {[{ name: "Report engine", icon: FileBarChart }, { name: "AI assistant", icon: Bot }, { name: "Data connection", icon: Landmark }].map((service) => (
              <li key={service.name} className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-muted"><service.icon className="size-4" aria-hidden="true" /></span><span className="flex-1">{service.name}</span><span className="flex items-center gap-1.5 text-xs text-[var(--status-success)]"><span className="size-1.5 rounded-full bg-current" aria-hidden="true" />Operational</span></li>
            ))}
          </ul>
        </aside>
      </div>
    </div>
  );
}
